/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "RPC_ampliacion.h"
#include "proxy-rpc.h"

int login_peticion(char *host, char*user, char *op, char *fichero)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	struct peticion_RPC registrar_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, LOGIN, LOGINVER1, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (-1);
	}
#endif	/* DEBUG */

    strcpy(registrar_1_arg1.nombre,user); 
    strcpy(registrar_1_arg1.operacion,op); 
    strcpy(registrar_1_arg1.fichero, fichero);

	retval_1 = registrar_1(registrar_1_arg1, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
    return result_1;
#endif	 /* DEBUG */
}