/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "RPC_ampliacion.h"

int login_1(char *host, char*user, char *op, char *fichero)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	struct peticion_RPC registrar_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, LOGIN, LOGINVER1, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (-1);
	}
#endif	/* DEBUG */

    strcpy(registrar_1_arg1.nombre,user); 
    strcpy(registrar_1_arg1.operacion,op); 
    strcpy(registrar_1_arg1.fichero, fichero);

	retval_1 = registrar_1(registrar_1_arg1, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
    return result_1;
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
    char *host  = getenv("LOG_RPC_IP");
    int ret;

    if(host == NULL){
        exit(-1);
    }

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

    login_1(host,"usuario- 1","SEND","");
	login_1 (host, "usuario-1", "SENDATTACH","/tmp/file1.txt");
    exit (0);
}
