/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_AMPLIACION_H_RPCGEN
#define _RPC_AMPLIACION_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct peticion_RPC {
	char nombre[256];
	char operacion[256];
	char fichero[256];
};
typedef struct peticion_RPC peticion_RPC;

#define LOGIN 100525454
#define LOGINVER1 1

#if defined(__STDC__) || defined(__cplusplus)
#define registrar 1
extern  enum clnt_stat registrar_1(struct peticion_RPC , int *, CLIENT *);
extern  bool_t registrar_1_svc(struct peticion_RPC , int *, struct svc_req *);
extern int login_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define registrar 1
extern  enum clnt_stat registrar_1();
extern  bool_t registrar_1_svc();
extern int login_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_peticion_RPC (XDR *, peticion_RPC*);

#else /* K&R C */
extern bool_t xdr_peticion_RPC ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_AMPLIACION_H_RPCGEN */
