/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "RPC_ampliacion.h"

bool_t registrar_1_svc(struct peticion_RPC arg1, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
    if(strcmp(arg1.operacion, "SENDATTACH") == 0){
        printf("%s %s %s\n", arg1.nombre, arg1.operacion, arg1.fichero);
    }else{

        printf("%s %s\n",arg1.nombre, arg1.operacion);
    }
    // Resultado para el cliente
    *result = 1;

    // Resultado para el servidor
	return TRUE;
}

int
login_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
